name: Deploy
on: push # Con workflow_dispatch indicamos que se ejecutará manualmente. Con push se ejecutará cuando se pushea 
jobs: 
  first_job:
    runs-on: ubuntu-latest # Acá definimos nuestro runner.
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: user/app:latest
         